<a href="https://colab.research.google.com/github/Ramses-Monjaras/Data-Processing-Visualization/blob/main/Quiz_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [84]:
%reload_ext google.colab.data_table

In [85]:
from google.colab import auth
auth.authenticate_user()
print('Authenticated')

Authenticated

In [86]:
%%bigquery --project vizproject-488423
SELECT
  COUNT(*) as total_trips
FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips`

Query is running:   0%|          |

Downloading:   0%|          |

   total_trips
0      2271152

In [87]:
%%bigquery --project vizproject-488423
SELECT
  MAX(duration_minutes) as longest_trip_duration
FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips`

Query is running:   0%|          |

Downloading:   0%|          |

   longest_trip_duration
0                  34238

In [88]:
%%bigquery --project vizproject-488423
SELECT
  avg(duration_minutes) as avg_trip_duration
FROM `bigquery-public-data.austin_bikeshare.bikeshare_trips`

Query is running:   0%|          |

Downloading:   0%|          |

   avg_trip_duration
0          28.719181